name: 'ey_data_platform'
version: '1.0.0'
config-version: 2

profile: 'ey_data_platform'

model-paths: ["models"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  ey_data_platform:
    +materialized: table